export { ScreeningService, type ScreeningServiceOptions } from './service.ts'
export {
  MAX_UNIVERSE,
  STATIC_UNIVERSE,
  universeFromWatchlistGroups,
  type UniverseEntry,
  type UniverseProvider,
} from './service.ts'
export { ScreeningRunRepository } from './repository.ts'
export {
  SCREENING_STRATEGIES,
  extractFinancialMetrics,
  getScreeningStrategy,
  strategiesByFamily,
  type FinancialMetrics,
  type ScreeningStrategyDef,
  type StrategyContext,
  type StrategyFamily,
  type SymbolData,
} from './strategies.ts'
export {
  BREAKOUT_VOLUME_MULT,
  BREAKOUT_WINDOW,
  DIVIDEND_WINDOW_DAYS,
  DIVIDEND_YIELD_PCT,
  EARNINGS_WINDOW_DAYS,
  HIGH_ROE_PCT,
  HIGH_VOLUME_RATIO,
  LOW_PB,
  LOW_PE,
  MIN_DAY_MOVE_PCT,
  MOMENTUM_1M_PCT,
  MOMENTUM_3M_PCT,
  NEWS_SURGE_MIN,
  NEWS_SURGE_WINDOW_DAYS,
  OVERSOLD_3M_PCT,
  OVERSOLD_BELOW_SMA_PCT,
  QUALITY_GROWTH_PCT,
  QUALITY_MARGIN_PCT,
  QUALITY_ROE_PCT,
  RATING_UPSIDE_MIN_PCT,
  REVENUE_GROWTH_PCT,
  UNUSUAL_AMPLITUDE_MIN_PCT,
  UNUSUAL_AMPLITUDE_RATIO,
} from './strategies.ts'
