import type { CanonicalInstrument } from './instrument.ts';

/**
 * Seed catalog for first-version resolution. These are real listings used as
 * fixtures and as the default persisted alias map. This is not a complete
 * securities master.
 */
export const DEFAULT_INSTRUMENT_CATALOG: readonly CanonicalInstrument[] = [
  {
    instrumentId: 'XNAS:AAPL',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    nameAliases: ['Apple'],
    exchangeMic: 'XNAS',
    exchange: 'NASDAQ',
    market: 'US',
    country: 'US',
    assetType: 'equity',
    currency: 'USD',
    providerAliases: [
      { providerId: 'longbridge', symbol: 'AAPL.US' },
      { providerId: 'massive', symbol: 'AAPL' },
    ],
    externalIds: [{ type: 'isin', value: 'US0378331005' }],
  },
  {
    instrumentId: 'XNAS:TSLA',
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    nameAliases: ['Tesla'],
    exchangeMic: 'XNAS',
    exchange: 'NASDAQ',
    market: 'US',
    country: 'US',
    assetType: 'equity',
    currency: 'USD',
    providerAliases: [
      { providerId: 'longbridge', symbol: 'TSLA.US' },
      { providerId: 'massive', symbol: 'TSLA' },
    ],
    externalIds: [{ type: 'isin', value: 'US88160R1014' }],
  },
  {
    instrumentId: 'XNAS:NVDA',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    nameAliases: ['NVIDIA', 'Nvidia'],
    exchangeMic: 'XNAS',
    exchange: 'NASDAQ',
    market: 'US',
    country: 'US',
    assetType: 'equity',
    currency: 'USD',
    providerAliases: [
      { providerId: 'longbridge', symbol: 'NVDA.US' },
      { providerId: 'massive', symbol: 'NVDA' },
    ],
    externalIds: [{ type: 'isin', value: 'US67066G1040' }],
  },
  {
    instrumentId: 'XHKG:0700',
    symbol: '0700',
    name: 'Tencent Holdings Limited',
    nameAliases: ['Tencent', '腾讯控股'],
    exchangeMic: 'XHKG',
    exchange: 'HKEX',
    market: 'HK',
    country: 'HK',
    assetType: 'equity',
    currency: 'HKD',
    providerAliases: [{ providerId: 'longbridge', symbol: '0700.HK' }],
    externalIds: [{ type: 'isin', value: 'KYG875721634' }],
  },
  {
    instrumentId: 'XNYS:BABA',
    symbol: 'BABA',
    name: 'Alibaba Group Holding Limited',
    nameAliases: ['Alibaba'],
    exchangeMic: 'XNYS',
    exchange: 'NYSE',
    market: 'US',
    country: 'US',
    assetType: 'equity',
    currency: 'USD',
    providerAliases: [
      { providerId: 'longbridge', symbol: 'BABA.US' },
      { providerId: 'massive', symbol: 'BABA' },
    ],
    externalIds: [{ type: 'isin', value: 'US01609W1027' }],
  },
  {
    instrumentId: 'XHKG:9988',
    symbol: '9988',
    name: 'Alibaba Group Holding Limited',
    nameAliases: ['Alibaba'],
    exchangeMic: 'XHKG',
    exchange: 'HKEX',
    market: 'HK',
    country: 'HK',
    assetType: 'equity',
    currency: 'HKD',
    providerAliases: [{ providerId: 'longbridge', symbol: '9988.HK' }],
  },
];
